services:
  postgres-db:
    image: pgvector/pgvector:pg16
    container_name: meistre-postgres
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: meistre_user
      POSTGRES_PASSWORD: meistre_password
      POSTGRES_DB: meistre_db
    volumes:
      - meistre_postgres_data:/var/lib/postgresql/data

  ollama-server:
    image: ollama/ollama:latest
    container_name: meistre-ollama
    ports:
      - '11434:11434'
    volumes:
      - meistre_ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*

volumes:
  meistre_postgres_data:
  meistre_ollama_data: