spring:
  application:
    name: meistre-assistant
  docker:
    compose:
      enabled: false

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  datasource:
    url: jdbc:postgresql://localhost:5434/meistre_db
    username: meistre_user
    password: meistre_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  threads:
    virtual:
      enabled: true

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3
          temperature: 0.4
      embedding:
        options:
          model: nomic-embed-text
    vectorstore:
      pgvector:
        table-name: meistre_knowledge_vectors
        embedding-dimension-override: 768

resilience4j:
  circuitbreaker:
    instances:
      meistreChat:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        failure-rate-threshold: 50 # Abre o circuito se 50% das últimas 10 chamadas falharem
        wait-duration-in-open-state: 10000 # Espera 10 segundos antes de tentar reabrir
        slow-call-rate-threshold: 75 # Abre o circuito se 75% das chamadas forem lentas
        slow-call-duration-threshold: 30000 # Considera lenta uma resposta que demorar mais de 30s